version: '2.1'

services:

  db:
    container_name: db
    build: ./src/db
    image: tundaey/drinkmonitorapi_db:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0

  api:
    container_name: api
    build: .
    image: tundaey/drinkmonitorapi_api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/drinkmonitor_dev
      - DATABASE_TEST_URL=postgres://admin:admin@db:5432/drinkmonitor_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      db:
        condition: service_healthy
    links:
      - db