version: '2.1'

services:

  prod_db:
    container_name: prod_db
    build: ./src/db
    image: tundaey/drinkmonitorapi_prod_db:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0

  prod_api:
    container_name: prod_api
    build: .
    image: tundaey/drinkmonitorapi_prod_api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://admin:admin@prod_db:5432/drinkmonitor_dev
      - DATABASE_TEST_URL=postgres://admin:admin@prod_db:5432/drinkmonitor_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      prod_db:
        condition: service_healthy
    links:
      - prod_db