version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.2-ce-git
    working_directory: ~/drinkmonitor-api
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              curl \
              nodejs
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Dockerhub Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Spin up Docker containers
          command: docker-compose -f docker-compose-review.yml up --build -d
      - run:
          name: Test the api
          command: docker-compose -f docker-compose-review.yml run prod_api npm test
    deployment:
      latest:
        branch: master
        commands:
          - docker login -u $DOCKER_USER -p $DOCKER_PASS
          - docker-compose -f docker-compose-review.yml push
          - deploy.sh